# Generated by Django 4.2.7 on 2023-11-30 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='bolum',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='navbar',
            name='bolum_alt_1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='navbar',
            name='bolum_alt_2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='navbar',
            name='bolum_alt_3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='navbar',
            name='bolum_alt_4',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
