# Generated by Django 4.2.7 on 2023-11-30 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_navbar_akademik_navbar_akademik_alt_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='arastirma',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='navbar',
            name='arastirma_alt_1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='navbar',
            name='arastirma_alt_2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='navbar',
            name='ders',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='navbar',
            name='kalite',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='navbar',
            name='mezun',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='navbar',
            name='program',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='navbar',
            name='staj',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
