# Generated by Django 4.2.7 on 2023-12-01 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_navbar_arastirma_navbar_arastirma_alt_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navbar2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
