# Generated by Django 4.2.7 on 2023-12-01 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_navbar2'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='nokta',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
