# Generated by Django 4.2.7 on 2023-12-01 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_navbar_nokta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolum_ismi', models.CharField(blank=True, max_length=500, null=True)),
                ('duyuru', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
