# Generated by Django 4.2.7 on 2023-12-02 11:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_uygulamali'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(default=2023)),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
