# Generated by Django 4.2.7 on 2023-12-02 11:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='text2',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
