# Generated by Django 4.2.7 on 2023-12-05 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_footer_text2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navbar',
            options={'verbose_name': 'Country / State', 'verbose_name_plural': 'Countries / States'},
        ),
    ]
