# Generated by Django 4.2.7 on 2023-12-05 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_alter_navbar_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amac',
            options={'verbose_name': 'Amaç', 'verbose_name_plural': 'Bölüm amaçları'},
        ),
        migrations.AlterModelOptions(
            name='arastirma',
            options={'verbose_name': 'Araştırma', 'verbose_name_plural': 'Araştırma'},
        ),
        migrations.AlterModelOptions(
            name='bolum',
            options={'verbose_name': 'Bölüm', 'verbose_name_plural': 'Bölüm Hakkında'},
        ),
        migrations.AlterModelOptions(
            name='cikti',
            options={'verbose_name': 'Çıktı', 'verbose_name_plural': 'Bölüm Çıktısı'},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'İletişim form sayfası', 'verbose_name_plural': 'İletişim form sayfası'},
        ),
        migrations.AlterModelOptions(
            name='dersler',
            options={'verbose_name': 'Ders', 'verbose_name_plural': 'Ders İçerikleri'},
        ),
        migrations.AlterModelOptions(
            name='duyuru',
            options={'verbose_name': 'Duyuru', 'verbose_name_plural': 'Duyurular'},
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'Home', 'verbose_name_plural': 'Anasayfa Başlıkları'},
        ),
        migrations.AlterModelOptions(
            name='idare',
            options={'verbose_name': 'İdare', 'verbose_name_plural': 'İdare'},
        ),
        migrations.AlterModelOptions(
            name='i̇letisim',
            options={'verbose_name': 'İletişim sayfası', 'verbose_name_plural': 'İletişim sayfası'},
        ),
        migrations.AlterModelOptions(
            name='kalite',
            options={'verbose_name': 'Kalite', 'verbose_name_plural': 'Kalite Komisyonu'},
        ),
        migrations.AlterModelOptions(
            name='mezunlar',
            options={'verbose_name': 'Mezun', 'verbose_name_plural': 'Mezun Sistemi'},
        ),
        migrations.AlterModelOptions(
            name='navbar',
            options={'verbose_name': 'Navbar', 'verbose_name_plural': 'Navbardaki Başlıkların İsimleri'},
        ),
        migrations.AlterModelOptions(
            name='navbar2',
            options={'verbose_name': 'Navbar2', 'verbose_name_plural': 'İletişim ve sonradan eklenecek başlıkların isimleri '},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name': 'Program', 'verbose_name_plural': 'Akademik Program'},
        ),
        migrations.AlterModelOptions(
            name='staj',
            options={'verbose_name': 'Staj', 'verbose_name_plural': 'Staj'},
        ),
    ]
