# Generated by Django 4.2.7 on 2023-12-05 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_alter_amac_options_alter_arastirma_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analiz',
            options={'verbose_name': 'Analiz ve Fonksiyonlar Teorisi A.B.D', 'verbose_name_plural': 'Analiz ve Fonksiyonlar Teorisi A.B.D'},
        ),
        migrations.AlterModelOptions(
            name='bilgisayar',
            options={'verbose_name': 'Bilgisayar Bilimleri A.B.D.', 'verbose_name_plural': 'Bilgisayar Bilimleri A.B.D.'},
        ),
        migrations.AlterModelOptions(
            name='cebir',
            options={'verbose_name': 'Cebir ve Sayılar Teorisi A.B.D.', 'verbose_name_plural': 'Cebir ve Sayılar Teorisi A.B.D.'},
        ),
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name': 'Footer  A.B.D.', 'verbose_name_plural': 'Footer  A.B.D.'},
        ),
        migrations.AlterModelOptions(
            name='geometri',
            options={'verbose_name': 'Geometri A.B.D.', 'verbose_name_plural': 'Geometri A.B.D.'},
        ),
        migrations.AlterModelOptions(
            name='lojik',
            options={'verbose_name': 'Matematiğin Temelleri ve Lojik A.B.D.', 'verbose_name_plural': 'Matematiğin Temelleri ve Lojik A.B.D.'},
        ),
        migrations.AlterModelOptions(
            name='topoloji',
            options={'verbose_name': 'Topoloji  A.B.D.', 'verbose_name_plural': 'Topoloji  A.B.D.'},
        ),
        migrations.AlterModelOptions(
            name='uygulamali',
            options={'verbose_name': 'Uygulamalı Matematik  A.B.D.', 'verbose_name_plural': 'Uygulamalı Matematik  A.B.D.'},
        ),
    ]
