# Generated by Django 4.2.7 on 2023-12-11 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_alter_analiz_options_alter_bilgisayar_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name': 'Footer', 'verbose_name_plural': 'Footer'},
        ),
    ]
