# Generated by Django 4.2.7 on 2023-12-13 11:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_alter_footer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='idare',
            name='text_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
