# Generated by Django 4.2.7 on 2023-12-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_idare_tittle_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='bolum_eng',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
