# Generated by Django 4.2.7 on 2023-12-13 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_navbar_bolum_eng'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='bolum_alt_1_eng',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='navbar',
            name='bolum_alt_2_eng',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='navbar',
            name='bolum_alt_3_eng',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
