# Generated by Django 4.2.7 on 2023-12-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_navbar_akademik_eng_navbar_arastirma_alt_1_eng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar2',
            name='name_eng',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
