# Generated by Django 4.2.7 on 2023-12-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_navbar2_name_eng'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='bolum_ismi_eng',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='duyuru_eng',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='navbar',
            name='akademik_alt_1_eng',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='navbar',
            name='akademik_alt_2_eng',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='navbar',
            name='akademik_alt_3_eng',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='navbar',
            name='akademik_alt_4_eng',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='navbar',
            name='akademik_alt_5_eng',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='navbar',
            name='akademik_alt_6_eng',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='navbar',
            name='akademik_alt_7_eng',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
