# Generated by Django 4.2.7 on 2024-02-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_home_bolum_ismi_eng_home_duyuru_eng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='home'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='date',
            field=models.IntegerField(default=2024),
        ),
    ]
